server:
  port: 9001

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: subrental-order
          uri: lb://subrental-order
          predicates:
            - Path=/api/orders/**
        - id: subrental-billing
          uri: lb://subrental-billing
          predicates:
            - Path=/api/billings/**
        - id: subrental-orderproduct
          uri: lb://subrental-orderproduct
          predicates:
            - Path=/api/orderproducts/**
        - id: subrental-product
          uri: lb://subrental-product
          predicates:
            - Path=/api/products/**
      default-filters:
        - name: GlobalAuthFilter

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"